### ISSUE TITLE
Client Crash on Launch

### ISSUE THREAD

**Issue by Sisyphus-1942** [Griefed/Survive-Create-Prosper-4#4]
* **Please tell us about your environment:**

   - Survive Create Prosper version: 
   - Operating system: 
   - Java version: 
   
* **Logs:**

  - latest.log: https://pastebin.com/J1ZxjErG

* **What is the current behavior?**

The client crashes on launch, this has happened for several versions to include the latest version.

My best guess is its one of the biome mods due to these two lines.
```
[11:43:09] [pool-3-thread-1/INFO]: Patching net/minecraft/loot/functions/EnchantRandomly
[11:43:09] [pool-3-thread-1/ERROR]: Critical injection failure: LVT in net/minecraft/world/gen/FlatGenerationSettings::func_236942_c_()Lnet/minecraft/world/biome/Biome; has incompatible changes at opcode 106 in callback net/minecraft/world/gen/FlatGenerationSettings::addCrashDetails.
```

**Comment by Griefed** [comment]
Heya Sisyphus-1942,
thanks for reporting this issue. I'll take a look at it now. 🙂

Cheers,
Griefed

**Comment by Griefed** [comment]
For future issues, please fill out the following section as it helps with identifying the problem, source and finding a solution.
> - Please tell us about your environment:
>     - Survive Create Prosper version:
>     - Operating system:
>     - Java version:

### Which launcher did you use to download and install Survive Create Prosper 4? 

I've just tried a fresh and clean install with both GDLauncher and the Overwolf Curseforge app for Survive Create Prosper 4 version 4.6.14 and in both instances, Minecraft starts up perfectly fine


### The log states that you are running Java version 1.8.0_51. Please update to at least 1.8.0_291.

Speaking from personal experience, I've encountered problems with an outdated Java version in the past. Please update your Java installation to at least the aforementioned version. See above where I mentioned testing 4.6.14 with both GDLauncher and Overworlf Curseforge app.
Strangely though, even when I use the Java installation which is installed together with Curseforge, that being the very same version you are using, the client does not crash on my side either.


### Have you added any mods to the modpack or otherwise customized it?

Please tell me whether you have added any mods to Survive Create Prosper yourself, such as Optifine or anything like that.

**Comment by Sisyphus-1942** [comment]
Sorry thought I include those, it was a fresh install of the survive create prosper 4.6.14 on curseforge launcher, os is windows 10 2021 2. I am updating java now, for some reason the update checker wasnt finding it so I'm installing manually.
edit: updating java and manually updating the binary path instead of letting curseforge find it seemed to fix the issue. Thank you

**Comment by Griefed** [comment]
No problem, happens to the best of us.

Very glad to hear that updating Java fixed the issue for you. Don't hesitate to open a new issue should you encounter any more problems. 🙂

Cheers,
Griefed
