### ISSUE TITLE
Game crash when typing "staff" in the item explorer 

### ISSUE THREAD

**Issue by Geleu1** [Griefed/Survive-Create-Prosper-4#6]
* **Please tell us about your environment:**

   - Survive Create Prosper version: 4.7.0
   - Operating system: Windows 10 21H2
   - Java version: Build 1.8.0_321-b07
   
* **Logs:**

  - crash-log: https://privatebin.net/?567227094bf8bace#DVGxEYNjMGcVgqGuDJweDVLG41VSgfXmpb2MyHaQKgpK
  - latest.log: https://privatebin.net/?6912f0561d917bd2#4bxXbmrsJLkSaPwcGQJoADWUbREYsSCz7PLKythHM4ba

* **What is the current behavior?**

Step 1: Open the inventory
Step 2: In the item explorer type "sta"
Step 3: The moment the letter "f" is typed in the game crashes
Step 4: Wait another 10min for it to launch

* **What is the expected behavior?**

The list of items that contain "staff" in the name should appear, but the game instant crashes when "f" is added

* **Other information / Questions** 
 I do have optifine installed, i don't know if that has any correlation

   
I allocated 9gb of RAM to the game

The game doesn't crash if i type "battlestaff" so it's not the problem isn't the button "f" 

I found the error after unlocking he battlestaff as a weapon, so i wanted to see how to craft it. Searched "Battlestaff" and got nothing so i searched "staff" instead.

Also the world has cheats on

**Comment by Geleu1** [comment]
Optifine isn't the problem, error persists after removing it

**Comment by Geleu1** [comment]
When only typing "af" i can go as far as page 34-35/40, the game instant crashes when going to the next page

The staffs from the "Reliquary" mode aren't the problem

**Comment by Griefed** [comment]
Heya Geleu1,

thanks for reporting this issue. I'll investigate your logs and try to reproduce this behaviour on my end and will get back to you when I found something.

Cheers,
Griefed

**Comment by Griefed** [comment]
Unfortunately, I can not reproduce this issue on my end.

I did however notice that your logs state 

> ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_51 by Oracle Corporation

and

> JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)

This indicates that you are using an outdated version of Java 8 in order to run Minecraft. This may be caused by the Overwolf CurseForge launcher or any other launcher you may be using.

Please try to remedy this by downloading and installing the [Adoptium JDK8](https://adoptium.net/download?link=https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u322-b06/OpenJDK8U-jdk_x64_windows_hotspot_8u322b06.msi), which will install JDK8u322. 

After you've installed the new Java version, you need to tell your launcher to use said Java version. Depending on which launcher you are using, the setting for chaning the used Java version can be tricky to find. 

### Overwolf CurseForge: 
Hit the cog-symbol in the bottom left of the launcher-window, select Minecraft on the left under ***Game specific***, scroll to the bottom and select the desired Java version.
![image](https://user-images.githubusercontent.com/44273438/161399003-fccd8b05-b541-4a82-97b2-b89c69ca56aa.png)

### GDLauncher:
Click the cog-symbol in th top right. Select Java on the left. If ***Autodetect Java Path*** is enabled, then disable it and run the ***Run JAva Setup again*** with manual setup and select your newly instaslled Java version. Afterwards, it should look similar to this:
![image](https://user-images.githubusercontent.com/44273438/161399425-68e0762b-32ad-47ec-afcc-941f71745e43.png)

**Comment by Geleu1** [comment]
I installed the new version and now it works, Thanks, though i think the problem was with the draconic evolution items.
